### ISSUE TITLE
execute-all.sh get error on fail:1

### ISSUE THREAD

**Issue by vanshu** [anestisb/android-prepare-vendor#140]
## on ubuntu 18.04 

./execute-all.sh --device bullhead --buildID OPM7.181205.001 --output "${BUILD_DIR}/vendor/android-prepare-vendor"

then get response error code : Fail:1

**Comment by anestisb** [comment]
@vanshu thanks for reporting. Fixed in https://github.com/anestisb/android-prepare-vendor/commit/c6b4acb422be92ab0b88f413fa24159ad629dee7. If the output directory does not exist the realpath wrapper was failing to resolve the absolute path and the script has a very aggressive error handling. The patch create the output directory if does not exist.
