### ISSUE TITLE
How to build google pixel AOSP such that not allowing device to boot into recovery

### ISSUE THREAD

**Issue by vamsirocks** [anestisb/android-prepare-vendor#64]
Hi ,
I want help regarding, how to build pixel AOSP such that my device cant enter into recovery mode . Please provide me suggestions in AOSP such that my custom build comes without recovery partition.

**Comment by anestisb** [comment]
I don't think this issue/query is related to the vendor blobs creation process that is covered by this project.

From time to time I tried to answer a few questions that were not exactly part of the vendor blobs integration, but part of the general AOSP build configuration, since that helped me to better test the configuration profiles of the supported devices. However, general Android optimization/tweaking of the AOSP codebase is beyond the purpose of this project. You need to seek answers at more relative places, such as the Android mailing group lists.

Closing the issue as invalid.
